
ARDUINO_DIR  = /usr/share/arduino
#ARDUINO_LIBS =  /home/pi/rfid-arduino-raspberry/sketch/rfid/src/MFRC522.
ARDUINO_LIBS = SPI MFRC522
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
