
ARDUINO_DIR  = /usr/share/arduino
#ARDUINO_DIR  = /home/pi/arduino-1.5.7

#ARDUINO_LIBS =  /home/pi/rfid-arduino-raspberry/sketch/rfid/src/MFRC522.
ARDUINO_LIBS = SPI MFRC522
BOARD_TAG    = uno
#ARDUINO_PORT = /dev/ttyACM0
ARDUINO_PORT = /dev/ttyAMA0
include /usr/share/arduino/Arduino.mk
